In [1]:
from lie_learn.representations.SO3 import spherical_harmonics
import lie_learn.spaces.S2 as S2
import numpy as np

In [2]:
def generate_sh(L, theta, phi):
    irreps = np.arange(L + 1)
    ls = [[ls] * (2 * ls + 1) for ls in irreps]
    ls = np.array(
       [ll for sublist in ls for ll in sublist]
    )  # 0, 1, 1, 1, 2, 2, 2, 2, 2, ...
    
    ms = [list(range(-ls, ls + 1)) for ls in irreps]
    ms = np.array(
       [mm for sublist in ms for mm in sublist]
    )  # 0, -1, 0, 1, -2, -1, 0, 1, 2, ...

    Y = spherical_harmonics.sh(
       ls[:, None, None],
       ms[:, None, None],
       theta[None, :, :],
       phi[None, :, :],
       field="real",
       normalization="quantum",
       condon_shortley=True,
    )

    return Y

In [17]:
theta, phi = S2.meshgrid(b=20, grid_type="Driscoll-Healy")
Y = generate_sh(1, theta, phi)

In [18]:
Y[:,5,2]

array([ 0.28209479, -0.05778002,  0.45140986, -0.17782863])

In [19]:
Y[:,1,12]

array([ 0.28209479, -0.03645905,  0.48709631,  0.01184626])

In [28]:
t, p = np.meshgrid(np.array([theta[5,0], theta[1,0]]), np.array([phi[0,2], phi[0,12]]))
generate_sh(1, t, p)

array([[[ 0.28209479,  0.28209479],
        [ 0.28209479,  0.28209479]],

       [[-0.05778002, -0.01184626],
        [-0.17782863, -0.03645905]],

       [[ 0.45140986,  0.48709631],
        [ 0.45140986,  0.48709631]],

       [[-0.17782863, -0.03645905],
        [ 0.05778002,  0.01184626]]])

In [7]:
generate_sh(1, t, p)[:,0]

array([[ 0.28209479,  0.28209479],
       [-0.11650793, -0.04016301],
       [-0.31077743, -0.47099911],
       [-0.35857455, -0.12360902]])

In [8]:
spherical_harmonics.sh(1,-1, theta[5,0], phi[0,2], field="real",
       normalization="quantum",
       condon_shortley=True)

-0.11650793365745224

In [9]:
theta.shape

(20, 40)

In [10]:
phi.shape

(20, 40)

In [11]:
t

array([[2.26016958, 2.87234737],
       [2.26016958, 2.87234737]])

In [12]:
p

array([[0.31415927, 0.31415927],
       [1.88495559, 1.88495559]])

In [36]:
import torch
t, p = np.array([theta[5,0], theta[1,0]]), np.array([phi[0,2], phi[0,12]])
torch.tensor(generate_sh(1, t.reshape(-1,1), p.reshape(-1,1))).permute(1,0,2)[1]

tensor([[ 0.2821],
        [-0.0365],
        [ 0.4871],
        [ 0.0118]], dtype=torch.float64)

In [37]:
t.reshape(-1,1).shape

(2, 1)

In [14]:
theta, phi = S2.meshgrid(b=20, grid_type='Driscoll-Healy')

In [15]:
theta[:,0]

array([0.        , 0.07853982, 0.15707963, 0.23561945, 0.31415927,
       0.39269908, 0.4712389 , 0.54977871, 0.62831853, 0.70685835,
       0.78539816, 0.86393798, 0.9424778 , 1.02101761, 1.09955743,
       1.17809725, 1.25663706, 1.33517688, 1.41371669, 1.49225651,
       1.57079633, 1.64933614, 1.72787596, 1.80641578, 1.88495559,
       1.96349541, 2.04203522, 2.12057504, 2.19911486, 2.27765467,
       2.35619449, 2.43473431, 2.51327412, 2.59181394, 2.67035376,
       2.74889357, 2.82743339, 2.9059732 , 2.98451302, 3.06305284])

In [16]:
phi[0,:]

array([0.        , 0.15707963, 0.31415927, 0.4712389 , 0.62831853,
       0.78539816, 0.9424778 , 1.09955743, 1.25663706, 1.41371669,
       1.57079633, 1.72787596, 1.88495559, 2.04203522, 2.19911486,
       2.35619449, 2.51327412, 2.67035376, 2.82743339, 2.98451302,
       3.14159265, 3.29867229, 3.45575192, 3.61283155, 3.76991118,
       3.92699082, 4.08407045, 4.24115008, 4.39822972, 4.55530935,
       4.71238898, 4.86946861, 5.02654825, 5.18362788, 5.34070751,
       5.49778714, 5.65486678, 5.81194641, 5.96902604, 6.12610567])